### ISSUE TITLE
Develop грана

### ISSUE THREAD

**Issue by miljanuscumlic** [turanjanin/cirilizator#17]
Предлажем да се направи develop грана да се репо приближи GitFlow-у.
Онда би се feature/PR гране спајале на develop, а develop би се спајао на master тек када је спреман нови release.

**Comment by rammba** [comment]
Мени ово звучи као добра идеја.

**Comment by turanjanin** [comment]
Иако на већини пројеката користим комбинацију master, develop и feature грана, мислим да овде таква организација не би превише помогла. 

Ми тренутно master користимо као develop а у тренутку када се накупи довољно новина за објављивање нове верзије, ја тагујем нову верзију, ручно запакујем архиве и пошаљем их на store-ове. 

Ако неко жели да добије најновију ”стабилну” верзију, која је постављена на store, увек може да уради checkout тага. 

Да ли постоји нека додатна предност увођења нове, develop гране, коју тренуно не видим?

**Comment by miljanuscumlic** [comment]
Ок. Оваквом организацијом грана покривају се потребе пројекта. Иако одступа од стандарда, задовољиће развој пројекта.
Јоване, мислим да можеш да затвориш овај issue.
