### ISSUE TITLE
Video not showing on prva.rs

### ISSUE THREAD

**Issue by rammba** [turanjanin/cirilizator#18]
When extension is enabled for [prva.rs](https://www.prva.rs/) video can't be showed. When I click play button, I only hear audio. But when I enable extension on page with video, this bug will trigger when page is refreshed.
This happens on google chrome and edge, but everything works normally on mozilla firefox.

![Video not showing](https://user-images.githubusercontent.com/40705899/111076003-bb07db00-84ea-11eb-8d10-2861d8af4f67.png)

![Video showed](https://user-images.githubusercontent.com/40705899/111076005-bba07180-84ea-11eb-95d7-c0e8db3fbf76.png)

**Comment by turanjanin** [comment]
It seems that the problem was transliteration of CSS styles that were injected using javascript after video player is loaded. Can you confirm that issue is resolved now?

**Comment by rammba** [comment]
Yes, looks like it's working for both edge and chrome.
