### ISSUE TITLE
Није могуће искључити ћирилизацију бер поновног учитавања стране

### ISSUE THREAD

**Issue by veljkomilj** [turanjanin/cirilizator#2]
Пројекат је стварно сјајан! 

Приметио сам да у Фајерфоксу ако кликнем на икону за ћирилизацију два пута (укључим па искључим) да се текст не враћа на латиницу. 

Дакле репро је:
1. клик на дугме екстензије: текст прелази у ћирилицу
2. клик на дугме екстензије: текст остаје на ћирилици

Очекивано је да се на другом кораку врати на латиницу.

Поздрав!
Вељко

**Comment by turanjanin** [comment]
Здраво Вељко, хвала на пријави овог бага. Сада је то исправљено и биће укључено у наредну верзију екстензије.
