### ISSUE TITLE
Неисправан приказ малих слова ћ и ђ на сајту Н1инфо

### ISSUE THREAD

**Issue by miljanuscumlic** [turanjanin/cirilizator#5]
У Фајерфоксу 84.0.2 на страници:
https://rs.n1info.com/biznis/a572281-vlahovic-kopaonik-biznis-forum-najveci-konferencijski-dogadjaj-u-regionu/
мало слово ћ се приказује као мало слово ђ и обрнуто.

Чини ми се да ово важи за цео сајт. Велика слова Ћ и Ђ се исправно приказују.

Одличан додатак! :+1:

**Comment by turanjanin** [comment]
Проблем је, по свему судећи, у фонту који сајт ове телевизије користи.

Правила пресловљавања су иста за све. Уколико пробаш да копираш текст чланка и налепиш га негде другде, приметићеш да пише Влаховић, а не Влаховиђ, само фонт који Н1инфо користи из неког разлога има замењено мало слово ђ и ћ.

Све постаје још чудније уколико исти фонт, Exo 2, [проверимо на Google Fonts сајту](https://fonts.google.com/specimen/Exo+2?preview.text=%D0%92%D0%BB%D0%B0%D1%85%D0%BE%D0%B2%D0%B8%D1%9B:%20%D0%9A%D0%BE%D0%BF%D0%B0%D0%BE%D0%BD%D0%B8%D0%BA%20%D0%B1%D0%B8%D0%B7%D0%BD%D0%B8%D1%81%20%D1%84%D0%BE%D1%80%D1%83%D0%BC%20%D0%BD%D0%B0%D1%98%D0%B2%D0%B5%D1%9B%D0%B8%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D1%98%D1%81%D0%BA%D0%B8%20%D0%B4%D0%BE%D0%B3%D0%B0%D1%92%D0%B0%D1%98%20%D1%83%20%D1%80%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%83&preview.text_type=custom) где проблем са заменом не постоји. Контактираћу сада редакцију телевизије, можда ће имати слуха да нам изађу у сусрет и реше проблем. У супротном, изгледа да ћу морати да додам изузетак за rs.n1info.com и да ć стварно пребацујем у ђ како би се текстови приказивали како треба.

**Comment by rammba** [comment]
Желео бих само да пријавим да се исто дешава и на сајту [Спорт Клуба](https://sportklub.rs/fudbal/premier-league/arsenal-i-ozil-se-dogovorili-sledeca-stanica-fenerbahce/).

**Comment by turanjanin** [comment]
И на Спорт клубу је исти узрок - Exo 2 фонт који има грешку и не приказује ђ и ћ како треба.

Пре три дана сам послао мејл на webredakcija@n1info.com, описао проблем и замолио их да то реше али нисам добио никакав одговор. Бојим се да то уопште није допрело до техничке екипе.

Шта мислите, да ли да чекамо и даље на њих да реше то или да направим изузетак за ове сајтове и đ пребацујем у ћ а ć у đ?

**Comment by rammba** [comment]
По мени има смисла убацити изузетак, а ако се они смилују да промене, лако ће бити обрисати изузетак. Надам се само да не постоје други портали који користе тај фонт.

**Comment by turanjanin** [comment]
Управо је објављена верзија 1.0 која прави изузетак са сајтове телевизије Н1 инфо и Спорт клуба и "исправља" приказ слова "ћ" и "ђ". Уколико се појави још неки сајт који има овај проблем, додаћемо га међу изузетке.

**Comment by milansusnjar** [comment]
Код мене се приказује неисправно ”ћ”, умјесто њега стоји ”ђ”.
https://n1info.rs/vesti/jovan-memedovic-se-oglasio-posle-tvrdnji-o-trosenju-novca-na-rts/

Можда је рјешење ставити да на поменутом сајту приказује текст другим фонтом, aко је могуће нпр. 
```
body * {
    font-family: "Times New Roman" !important;
}
```

**Comment by turanjanin** [comment]
N1 је у међувремену променио домене које користи, зато је ово решење престало да ради. Pull request #50 исправља то. 

Објавићу сада нову верзију екстензије која ће укључити и ову исправку.

**Comment by milansusnjar** [comment]
Код мене је и даље ово проблем.

https://n1info.rs/vesti/rezultati-pisa-testiranja-2022/
"Како су прошли ћаци из Србије?"
